/*************************************************************/
/* encoder擖椡張棟 */
/*************************************************************/
/***********************************************************************/
/*                                                                     */
/*  FILE        :input encoder.h                                       */
/*  DATE        :Fri, Apr 04, 2008                                     */
/*  DESCRIPTION :define the macro for initialization of sections.      */
/*  CPU GROUP   :35C                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.12).    */
/*                                                                     */
/***********************************************************************/

/***********************************************************/
/*  COMPILER for R8C/Tiny                                  */
/*                                                         */
/*  Copyright(c) 2004 Renesas Technology Corp.             */
/*  And Renesas Solutions Corp.,All Rights Reserved.       */
/*                                                         */
/*  input encoder .h                                       */
/*                                                         */
/*  clear for bss section                                  */
/*  transfer initialized data to data section              */
/*                                                         */
/*  note: Do not modify                                    */
/*                                                         */
/* $Date: 2007/06/14 01:49:49 $                            */
/* $Revision: 1.9.4.2.8.2 $                                */
/***********************************************************/ 

#ifndef _INPUT_ENCODER_H
#define _INPUT_ENCODER_H

#include "Sys.h"


/* #define H_HABA					0xa3		忋尷妋擣抣嫋梕暆 100mm乮姫偒宎120mm乯*/
#define TOO_S_PULSE_LENGTH		20	    /*堎忢抁蔬俳 800rpm ???*/
#define TOO_L_PULSE_LENGTH		0x1bc  /*0x00c8  0x01bc		堎忢蔬俳挿偝 444ms*/
/* #define BOUSOU_LONG_NOISE_PENA  5    		朶憱専抦拞丄挿偄僲僀僘傪庴怣偟偨偲偒偺儅僀僫僗抣 */

#define	TIME_25MSEC		0x0019			/* 25msec */
#define	TIME_21MSEC		0x0015			/* 21msec */
#define TIME_20MSEC		0x0014			/* 20msec */
#define TIME_19MSEC 		0x0013			/* 19msec */
#define TIME_17MSEC 		0x0011			/* 17msec */
#define TIME_16MSEC 		0x0010			/* 16msec */
#define TIME_15MSEC 		0x000F			/* 15msec */
#define TIME_14MSEC		0x000E			/* 12msec */
#define TIME_12MSEC 	   	0x000c			/* 12msec */
#define TIME_10MSEC 		0x000A			/* 10msec */

#define BIT_SHIFT_2 		2			/* 2bit僔僼僩梡 */
#define PW_TO_RPM 		7500000			/* palse_width to rpm  */
#define L_PULS			  100
#define KETA_10		 	   10
#define KETA_100 		  100
#define KETA_1000		 1000
#define HIGH_SPEED_PULSE 	15100			/* 20131   		偙傟埲忋憗偄僷儖僗偼俛憡傪挷傋側偄 5131 */
#define DIRECTION_CLOSE		    0      		/* 暵曽岦偺俛憡偺偁傞傋偒儗儀儖 */
#define FASTER_SPEED		40000

#define U1_SPEED_BEST		0			/* 0:懍搙傄偭偨傝 */
#define U1_SPEED_UP		1			/* 1:抶偄偺偱UP */
#define U1_SPEED_DOWN		2			/* 2:懍偄偺偱DOWN */

#define NORMAL_21MS_MORE_DUTY		109		/*109 脉冲宽度21ms以上的软启动后DUTY */
#define NORMAL_28MS_MORE_DUTY		50		/*50 脉冲宽度28ms以上的软启动后DUTY */
#define SOFT_START_20MS_LESS_DUTY	18		/*18 脉冲宽度小于20ms的软启动中DUTY */
#define SOFT_START_20MS_MORE_DUTY	24		/*105 脉冲宽度20ms以上的软启动中DUTY */

/* extern u1 u1g_c_no_plus;					棉猫皰菈敛堇笆拶冻堇 */
/* extern u2 u2g_c_interval_plus;				僷儖僗偑棃側偄帪娫傪僇僂儞僩 */

/* extern u1 u1g_count_abnormal_speed_pulse; */
extern u1 u1g_count_moveing_B; 				/*摦嶌拞B憡娔帇冻堇*/
extern u1 u1g_fg_final_state;
extern u1 u1g_fg_mid_state;
extern u1 u1g_fg_direction_pulse; 				/* 僷儖僗偺曽岦 */

extern u1 u1g_c_move_consist;  				/* flash偵摦嶌夞悢傪彂偔丂僷儖僗僇僂儞僩 */
extern u1 u1g_fg_move_consist;    				/* 忋偺曄悢偑250僷儖僗傪挻偊偨傜僼儔僌僆儞両 */
extern u4 u4g_plus_length;

extern u1 u1g_fg_input_encoder;
extern u4 u4g_d_rpm_before;

extern u2 u2g_d_rpm_current;
extern u1 u1g_cnt_change_mode;  		/*掆亄奐暵SW挿墴偟帪娫 忋尷儕僙僢僩*/
/* extern u1 u1g_c_check_out;						联梡弌椡帪娫冻堇 */

#endif


